### PR TITLE
Fix/relative url proxy handler

### LINKED ISSUE #774: Why would this be a bad request?
-bash-4.1$ export PATH=$PATH:~
-bash-4.1$ hoverctl status

+------------+----------+
| Hoverfly   | running  |
| Admin port |     8888 |
| Proxy port |     8500 |
| Proxy type | forward  |
| Mode       | capture  |
| Middleware | disabled |
+------------+----------+
-bash-4.1$ telnet localhost 8500
Trying ::1...
telnet: connect to address ::1: Connection refused
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
GET / HTTP/1.1
Host: thecure.com
User-Agent: Mozilla/5.0 (compatible; Yahoo! Slurp; http://help.yahoo.com/help/us/ysearch/slurp) .default/1538949339-2
Accept: */*

HTTP/1.1 500 Internal Server Error
Content-Type: text/plain; charset=utf-8
X-Content-Type-Options: nosniff
Date: Sun, 07 Oct 2018 23:33:21 GMT
Content-Length: 64

This is a proxy server. Does not respond to non-proxy requests.
^]

telnet> quit
Connection closed.
-bash-4.1$ 

https://github.com/SpectoLabs/goproxy/blob/master/proxy.go#L108-L110

Why does the url has to be absolute? If a Host header is provided

### PR DESCRIPTION
**Pull request by lobovit**
## Problem

When an HTTP/1.1 client sends a request with a relative URL (path only, no scheme/host) and a `Host` header a valid pattern per RFC 7230 goproxy routes it to `NonproxyHandler`. The default implementation returns `500 "This is a proxy server"`, making Hoverfly appear broken for clients that rely on this behaviour (e.g. some HTTP libraries and CLI tools).

Reproduces with:
```
curl --proxy http://localhost:8500 http://example.com
```

## Fix

Override `NonproxyHandler` in `NewProxy` to reconstruct the absolute URL from the `Host` header and re-dispatch the request through the normal proxy pipeline:

- Returns `400 Bad Request` if the `Host` header is absent (HTTP/1.0 style request with no host information  cannot be forwarded).
- Returns `500` (original behaviour) if the `Host` port matches the proxy's own port, preventing infinite recursion when a client connects directly to Hoverfly instead of using it as a proxy.
- Otherwise sets `r.URL.Scheme = "http"` and `r.URL.Host = r.Host`, then calls `proxy.ServeHTTP` the same pattern already used by `NewWebserverProxy`.

## Testing

Three regression tests added to `core/proxy_test.go` using raw TCP (required because `http.DefaultClient` always produces absolute URLs and would bypass `NonproxyHandler`):

- `Test_NewProxy_ShouldReturn400ForRelativeURLWithNoHostHeader`
- `Test_NewProxy_ShouldHandleRelativeURLWithHostHeader`
- `Test_NewProxy_ShouldReturn500WhenRelativeURLHostIsProxyItself`

Closes #774
```

### CODE REVIEW

**Comment by tommysitu** [comment]
hi @scovl thanks for your contributions! Just let you know that I will be offline for the next few days in case you're wondering why no one picks up the review. 

no sure if @marcoioco is around, otherwise i will check these out as soon as I can!

**Comment by scovl** [comment]
> hi @scovl thanks for your contributions! Just let you know that I will be offline for the next few days in case you're wondering why no one picks up the review.
> 
> no sure if @marcoioco is around, otherwise i will check these out as soon as I can!

Np, dude!
Ty!

**Comment by marcoioco** [comment]
@scovl thanks. Will review this in a few days.

File: core/proxy.go [hunk 1]
```diff
@@ -30,6 +33,27 @@ func NewProxy(hoverfly *Hoverfly) *goproxy.ProxyHttpServer {
...
 	proxy := goproxy.NewProxyHttpServer()
 
+	// Fix #774: HTTP/1.1 clients may send requests with a relative URL (path only) and a Host header.
+	// goproxy's default NonproxyHandler returns 500 for these. Reconstruct the absolute URL from the
+	// Host header so the request is processed normally, matching the behaviour of NewWebserverProxy.
+	//
+	// Guard: if the Host header targets the proxy's own port the client is connecting directly to
+	// Hoverfly (not using it as a proxy). In that case keep the original 500 "is a proxy server"
+	// response — forwarding to ourselves would cause infinite recursion or a panic.
+	proxy.NonproxyHandler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
```
Comment (tommysitu) [inline core/proxy.go:43]: does it override the default goproxy implementation?

Comment (scovl) [reply core/proxy.go:43]: Yes, it overrides the default goproxy `NonproxyHandler`, which returns HTTP 500 for all non-proxy requests. The new handler reconstructs the absolute URL from the `Host` header and re-dispatches the request through `proxy.ServeHTTP`, enabling HTTP/1.1 clients that send relative URLs to be handled correctly. 

> The original 500 behavior is preserved only when the `Host` targets the proxy's own port, to prevent infinite recursion.

Comment (tommysitu) [reply core/proxy.go:43]: Great! I think this should fix the issue while improving the existing non-proxy request check.

**Review by tommysitu — APPROVED** [review]
Nice fix — the approach is sound and the placement right after goproxy.NewProxyHttpServer() is correct, since it overrides the default NonproxyHandler before any other handlers are wired.

RFC compliance. HTTP/1.1 mandates a Host header (RFC 7230 §5.4), so the 400 for missing Host is correct. HTTP/1.0 clients without Host genuinely can't be reconstructed — 400 is the only sane response there too.

HTTPS scope. Hard-coding scheme = "http" is fine — raw TCP clients like telnet can't do TLS anyway, and HTTPS on the proxy port requires CONNECT. 

Good test coverage too. Well done!
